name: Java Linter

on: [pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install Checkstyle
        run: |
          wget -qO- https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.3.1/checkstyle-10.3.1-all.jar > checkstyle.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c google_checks.xml $(find . -name "*.java" | grep -v "/build/")
